CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email    TEXT NOT NULL UNIQUE,
    passHash BYTEA NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email ON users(email);

CREATE TABLE IF NOT EXISTS user_roles (
                                          user_id INTEGER REFERENCES users(id),
                                          role VARCHAR(50) NOT NULL,
                                          PRIMARY KEY (user_id, role)
);

CREATE TABLE IF NOT EXISTS apps
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE ,
    secret TEXT NOT NULL UNIQUE
);