env: "local" # prod, dev
token_ttl: 12h

db:
  host: "localhost"
  port: "5432"
  username: "postgres"
  dbname: "sso_db"

grpc:
  host: "0.0.0.0"       # слушать внутри контейнера на всех интерфейсах
  port: "44044"
  timeout: 10h          # если нужно